title: Dmitri Spiropoulos
description: Data Engineer & Analytics Professional · Newsletter Creator · Builder
url: "https://Djonathon.github.io"
baseurl: ""
author: Dmitri Spiropoulos
email: ""

plugins:
  - jekyll-seo-tag

sass:
  style: compressed

markdown: kramdown
